name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  # Linting & Formatting (Static Analysis)
  lint:
    name: 🧹 Linting and Formating
    runs-on: ubuntu-latest
    # env:
    #   MISE_ENABLE_TOOLS: "rust,actionlint,tombi,shellcheck,shfmt"
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          install_args: "rust actionlint tombi shellcheck shfmt"

      - run: mise settings ls
      - run: printenv | grep -i mise_
      - run: cargo version
      - run: actionlint --version
      - run: tombi --version
      - run: shellcheck --version
      - run: shfmt --version

